### ISSUE TITLE
Pipeline

### ISSUE THREAD

**Issue by zhangleigloria** [ThorntonLab/Cridland2013AnnotPipeline#1]
Dear sir,
         I am sorry to bother you in your busy schedule. Does this pipeline apply to other species, or just bees? Could you tell me about it?

**Comment by molpopgen** [comment]
This pipeline was originally developed for Drosophila.  The details are in the paper referred to in the heading at the repo's main page.

**Comment by zhangleigloria** [comment]
Thank you very much! One more question for you, is this pipeline for transcriptome data? I want to use this pipeline to find the transposons of mice.

**Comment by molpopgen** [comment]
> Thank you very much! One more question for you, is this pipeline for transcriptome data? I want to use this pipeline to find the transposons of mice.

No, it is for whole-genome resequencing.  These details are in the paper.

**Comment by zhangleigloria** [comment]
Ok, I read your paper 'Gene Expression Variation in Drosophila melanogaster Due to Rare Transposable Element Insertion Alleles of Large Effect' . For transcriptome data, the paper says that the annotated file was downloaded from the D. melanogaster reference version 5.31 and only identified the transcription start and stop locations for all transcripts. I would like to know how this paper found transposons on the transcript, is it the transposons annotation file obtained from the previous resequencing data, and are these two compared with 'blast' or the other methods? Is it convenient for you to tell me? Thank you very much!

**Comment by molpopgen** [comment]
The transcript annotation file is obtained by the method that you quoted--from Flybase, for the Dmel genome version 5.31.  Transposons are annotate via the methods in the 2013 paper referred to above and in the summary line for thsi repo.  A TE in a transcript is inferred by joining the two data sets.

I am going to close this issue now, as it is drifting away from a discussion about specific issues with this pipeline.  Most of your questions are answered in the published papers.

**Comment by zhangleigloria** [comment]
ok,thank you very much!------------------ 原始邮件 ------------------
发件人: "Kevin R. Thornton"<notifications@github.com>
发送时间: 2019年8月1日(星期四) 凌晨0:26
收件人: "ThorntonLab/Cridland2013AnnotPipeline"<Cridland2013AnnotPipeline@noreply.github.com>;
抄送: "zhangleigloria"<1277375850@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ThorntonLab/Cridland2013AnnotPipeline] Pipeline (#1)



The transcript annotation file is obtained by the method that you quoted--from Flybase, for the Dmel genome version 5.31.  Transposons are annotate via the methods in the 2013 paper referred to above and in the summary line for thsi repo.  A TE in a transcript is inferred by joining the two data sets.
 
I am going to close this issue now, as it is drifting away from a discussion about specific issues with this pipeline.  Most of your questions are answered in the published papers.
 
&mdash;
